"""
load_data.py  (MySQL version)
------------------------------
Loads the CSVs generated by generate_data.py into MySQL tables created
by sql/01_schema.sql.

Run:
    pip install pandas sqlalchemy pymysql --break-system-packages
    python load_data.py
"""

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

DB_USER = "root"
DB_PASSWORD = "Your_Password"
DB_HOST = "localhost"
DB_PORT = "3306"
DB_NAME = "credit_risk"

url = URL.create(
    "mysql+pymysql",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=int(DB_PORT),
    database=DB_NAME,
)
engine = create_engine(url)

dim_customer = pd.read_csv("../data/dim_customer.csv", parse_dates=["signup_date"])
dim_loan = pd.read_csv("../data/dim_loan.csv", parse_dates=["origination_date"])
dim_date = pd.read_csv("../data/dim_date.csv", parse_dates=["date_key"])
fact_payments = pd.read_csv("../data/fact_payments.csv", parse_dates=["due_date", "paid_date"])

# Load order matters because of foreign keys:
# customer -> loan -> date -> payments (payments FKs to both loan and date)
dim_customer.to_sql("dim_customer", engine, if_exists="append", index=False)
print(f"Loaded {len(dim_customer)} rows into dim_customer")

dim_loan.to_sql("dim_loan", engine, if_exists="append", index=False)
print(f"Loaded {len(dim_loan)} rows into dim_loan")

dim_date.to_sql("dim_date", engine, if_exists="append", index=False, chunksize=2000)
print(f"Loaded {len(dim_date)} rows into dim_date")

fact_payments.to_sql("fact_payments", engine, if_exists="append", index=False, chunksize=5000)
print(f"Loaded {len(fact_payments)} rows into fact_payments")

print("Done. Data is in the credit_risk database.")
